### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by bubnenkoff** [chrishalebarnes/quill.d#1]
Examples please :)

**Comment by chrishalebarnes** [comment]
Writing the readme now! In the mean time there are a ton of examples embedded in the [doc comments](https://github.com/chrishalebarnes/quill.d/blob/master/source/quill/database.d#L97) and in the [tests](https://github.com/chrishalebarnes/quill.d/blob/master/source/quill/database.d#L661)

**Comment by chrishalebarnes** [comment]
All done, see [readme.md](https://github.com/chrishalebarnes/quill.d/blob/master/readme.md).
